### ISSUE TITLE
Conflict with cordova-plugin-androidx-adapter

### ISSUE THREAD

**Issue by biloge** [wf9a5m75/cordova-androidx-build#1]
Good morning, I have a big problem with cordova-plugin-androidx-adapter conflict that I can not found solution.
I need to use in Ionic 5 app, ionic native maps plugin and firebasex plugin.
Ionic native maps need cordova-androidx-build plugin and firebasex need cordova-plugin-androidx-adapter , but when I try to create platform, cordova-androidx-build plugin exit with error becouse it does't unsinstall cordova-plugin-androidx-adapter plugin.
Is there a solution?
Is possible to use Maps and Firebasex Plugin together? 
many thanks

**Comment by wf9a5m75** [comment]
Could you share yours one or an example project files on GitHub repository?
I need to reproduce the situation.

**Comment by biloge** [comment]
Test is simply, I had create a blank app here :  https://github.com/biloge/testApp

This is what you need to do to emulate the problem : 

Create new blank Ionic Project 6.10.0
add cordova
```
ionic cordova plugin add cordova-plugin-firebasex
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```


```
D:\Progetti\testApp> ionic cordova build android
> cordova.cmd platform add android --save
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.ionic.starter
        Name: MyApp
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Installing "cordova-plugin-firebasex" for android
Installing "cordova-plugin-androidx" for android
Installing "cordova-plugin-androidx-adapter" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-googlemaps" for android
Installing "cordova-androidx-build" for android
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app

      Official document https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/README.md Please consider to buy a beer for us 🍺 https://github.com/mapsplugin/cordova-plugin-googlemaps#buy-us-a-beer

--[cordova-androidx-build]------------------------
Since cordova-plugin-androidx-adapter breaks cordova-androidx-build code,
uninstall cordova-plugin-androidx-adapter automatically.
-----------------------------------------------------
Command failed: cordova plugin rm cordova-plugin-androidx-adapter 2>&1

[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add android --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by wf9a5m75** [comment]
```
Since cordova-plugin-androidx-adapter breaks cordova-androidx-build code,
uninstall cordova-plugin-androidx-adapter automatically.
```

This is true. Because `cordova-plugin-androidx-adapter` is not perfect for me. It breaks `cordova-plugin-googlemaps`.
That's why I created this plugin.

**Comment by wf9a5m75** [comment]
You need to uninstall `cordova-plugin-androidx-adapter`.
This plugin takes over instead of `cordova-plugin-androidx-adapter`

**Comment by wf9a5m75** [comment]
I could not install modules...

```
$ npm i

> fsevents@1.2.13 install /Users/masashi/Documents/workspace/test/testApp/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/masashi/Documents/workspace/test/testApp/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:131:20)
    at Object.runInThisContext (vm.js:297:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/masashi/Documents/workspace/test/testApp/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/masashi/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/masashi/.nvm/versions/node/v13.12.0/bin/node" "/Users/masashi/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/masashi/Documents/workspace/test/testApp/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> fsevents@1.2.13 install /Users/masashi/Documents/workspace/test/testApp/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/masashi/Documents/workspace/test/testApp/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:131:20)
    at Object.runInThisContext (vm.js:297:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/masashi/Documents/workspace/test/testApp/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/masashi/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/masashi/.nvm/versions/node/v13.12.0/bin/node" "/Users/masashi/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/masashi/Documents/workspace/test/testApp/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> core-js@3.6.4 postinstall /Users/masashi/Documents/workspace/test/testApp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> @angular/cli@9.1.9 postinstall /Users/masashi/Documents/workspace/test/testApp/node_modules/@angular/cli
> node ./bin/postinstall/script.js

added 1546 packages from 1253 contributors and audited 1548 packages in 40.565s

52 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

```

**Comment by wf9a5m75** [comment]
I think you just need to do:

```
$> ionic cordova plugin rm cordova-plugin-androidx-adapter
```

**Comment by wf9a5m75** [comment]
Ok, I got the more details.

`cordova-plugin-firebasex` requires `cordova-plugin-androidx-adapter`, but this plugin conflicts with it.

Unfortunately, there is no solution at this time. 
You need to choose `cordova-plugin-googlemaps` or `cordova-plugin-firebasex`.

Please ask to @dpa99c to remove the requirement of `cordova-plugin-androidx-adapter`

**Comment by wf9a5m75** [comment]
Let's see... hold on. I got an idea to solve this problem.

**Comment by wf9a5m75** [comment]
Ok, I managed this problem.

cordova-androidx-build@1.0.4 handles this conflict problem very well.
Please reinstall `cordova-androidx-build`.

```
$ ionic cordova plugin rm cordova-androidx-build --force
$ ionic cordova plugin add cordova-androidx-build
```

**Comment by biloge** [comment]
Thank you so much, I will try It next monday, and I will tell you if works

Il ven 19 giu 2020, 21:16 Masashi Katsumata <notifications@github.com> ha
scritto:

**Comment by biloge** [comment]
Thank you, now it works! ;)
